config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'game', to: 'pages#game'
  get '/twoplayers', to: 'pages#twoplayers'
  post '/played', to: 'pages#played'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: %i[home hiscores invincible twoplayers]
  before_action :set_stats, only: %i[game]
  def home
  end

  def game
  end

  def hiscores
    @users = User.order('win DESC')
  end

  def played
    current_user.win += 1 if params[:win]
    current_user.losses += 1 if params[:loss]
    current_user.ties += 1 if params[:tie]
    current_user.save
  end

  def invincible 
  end

  def twoplayers
  end
  private

  def set_stats
    @wins = current_user.win
    @losses = current_user.losses
    @ties = current_user.ties
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active(path)
        current_page?(path) ? 'active' : ''
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTicTacToeProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%#= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-5">
  <div class="jumbotron" style="text-align:center">
    <h1>Tic Tac Toe</h1>
    <hr>
    <%= link_to "Two players!", twoplayers_path, class:'custom-btn btn-5' %>
    <br />
  </div>
</div>

app/views/pages/twoplayers.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.0.0/p5.min.js"></script>
<div class="container" style="text-align: center">
  <h1 id="scoreText" style="text-align: center">
    TicTacToe Two Player Game
  </h1>
  <div style="font-size: 32px; color:red;font-weight:bold;" id="result"></div>
  <button class='custom-btn btn-5' onClick="newGame()" data-title="Replay Tic Tac Toe">Replay Tic Tac Toe</button>
  <button class='custom-btn btn-5' onClick="freshGame()" data-title="New Game">Reset</button>
  <button class='custom-btn btn-5' onClick="endGame()" data-title="End">End</button>
  <div style="font-size: 32px" id="turn_player"></div>
  <span style="font-size: 32px;" id="size"></span>
</div>
<script>
  let boardSize = 3;
  let board = []
  var canvas;
  let currentPlayer
  let user1 = prompt("Enter Player 1 name:");
  let user2 = prompt("Enter Player 2 name:");
  let players = [user2, user1]
  let w;
  let h;
  var resultText = document.getElementById("result");
  var turnText = document.getElementById("turn_player");
  var sizeText = document.getElementById("size");
  var canvasOffset = resultText.getBoundingClientRect().bottom;
  let winner = null
  let isloop = true
  
  function setup() {
    canvas = createCanvas(500, 500);
  
    w = width/boardSize;
    h = height/boardSize;
    centerCanvas();
    initLabels()
  
    for(let i=0; i<boardSize; ++i) {
      let row = [];
      for(let j=0; j<boardSize; ++j) {
        row.push('');
      }
      board.push(row)
    }
    // boardSize = createSlider(2, 10, 3);
    currentPlayer = 1
  }
  
  function initLabels() {
    currentPlayer = 1
    turnText.innerHTML = players[currentPlayer] + "'s Turn";
    resultText.innerHTML = '';
  }
  
  function newGame() {
    w = width/boardSize;
    h = height/boardSize;
  
    board = []
  
    for(let i=0; i<boardSize; ++i) {
      let row = [];                                         
      for(let j=0; j<boardSize; ++j) {
        row.push('');
      }
      board.push(row)
    }
    currentPlayer = 1
  
    winner = null
    isloop = true
  
    resultText.innerHTML = '';
    sizeText.innerHTML = ('Size: '+boardSize)
    loop();
  }

  function freshGame(){
    location.reload();
  }

  function endGame(){
    let otherPlayer = (currentPlayer + 1) % 2;
    resultText.innerHTML = players[otherPlayer] + " is the winner!";
    isloop = false;
  }
  
  function keyReleased() {
      if (keyCode === 32 || keyCode === 13 || keyCode === 16 || keyCode === 17 || keyCode === 88 || keyCode === 9 || keyCode === 27 || keyCode === 46) {
          newGame();
      }
  }
  
  function addSize() {
    if(boardSize<15) {
      boardSize++;
      newGame();
    }
  }
  
  function subSize() {
    if(boardSize>2) {
      boardSize--;
      newGame();
    }
  }
  
  function isWinner() {
    for(let i=0;i<boardSize;++i) {
      let temp=board[i][0];
      if(temp=='') continue;
      for(let j=1;j<boardSize; ++j) {
        if(board[i][j] == '') {
          temp = '';
          break;
        }
        if(board[i][j] != temp) {
          temp = '';
          break;
        }
      }
      if(temp != '') {
        stroke(220, 0, 0);
        strokeWeight(8);
        line(w/4, w*(i+0.5), width-(w/4), w*(i+0.5))
        strokeWeight(4);
        stroke(0)
        return temp;
      }
    }
  
    for(let i=0;i<boardSize;++i) {
      let temp=board[0][i];
      if(temp=='') continue;
      for(let j=1;j<boardSize; ++j) {
        if(board[j][i] == '') {
          temp = '';
          break;
        }
        if(board[j][i] != temp) {
          temp = '';
          break;
        }
      }
      if(temp != '') {
        stroke(220, 0, 0);
        strokeWeight(8);
        line(w*(i+0.5), w/4, w*(i+0.5), height-(w/4))
        strokeWeight(4);
        stroke(0)
        return temp;
      }
    }
  
    let temp=board[0][0];
    if(temp != '') {
      for(let i=1;i<boardSize;++i) {
        if(board[i][i] == '') {
          temp = '';
          break;
        }
        if(board[i][i] != temp) {
          temp = '';
          break;
        }
      }
    }
    if(temp != '') {
      stroke(220, 0, 0);
      strokeWeight(8);
      line(w/4, w/4, width-(w/4), height-(w/4))
      strokeWeight(4);
      stroke(0)
      return temp;
    }
  
    temp=board[0][boardSize-1];
    if(temp != '') {
      for(let i=1;i<boardSize;++i) {
        if(board[i][boardSize-1-i] == '') {
          temp = '';
          break;
        }
        if(board[i][boardSize-1-i] != temp) {
          temp = '';
          break;
        }
      }
    }
    if(temp != '') {
      stroke(220, 0, 0);
      strokeWeight(8);
      line(width-(w/4), w/4, w/4, height-(w/4))
      strokeWeight(4);
      stroke(0)
      return temp;
    }
    for(let i=0; i<boardSize; ++i) {
      for(let j=0; j<boardSize; ++j) {
        if(board[i][j] == '') return null;
      }
    }
    return 'TIE';
  }
  
  function mousePressed() {
    if(mouseX > 0 && mouseX < width && mouseY > 0 && mouseY < height) {
      let j=Math.floor(mouseX/w);
      let i=Math.floor(mouseY/h);
      if(board[i][j] != '') return;
      board[i][j] = players[currentPlayer];
      currentPlayer = 1-currentPlayer;
    }
  }
  
  function updateText() {
    turnText.innerHTML = (players[currentPlayer] + "'s Turn")
  }
  
  function centerCanvas() {
      var canvasX = (windowWidth - width) / 2;
      var canvasY = (windowHeight - height) / 2 + canvasOffset;
      canvas.position(canvasX, canvasY);
  }
  
  function windowResized() {
      resizeCanvas(windowWidth, windowHeight - canvasOffset * 2);
      w = width / 3;
      h = height / 3;
      centerCanvas();
      drawGrid();
  }
  
  // The ticks of horizontal and vertical lines form the grid table
  function drawGrid() {
      line(w, 0, w, height);
      line(w * 2, 0, w * 2, height);
      line(0, h, width, h);
      line(0, h * 2, width, h * 2);
  }
  
  function draw() {
    if(isloop) {
      background(220);
      drawGrid();
      updateText();
      strokeWeight(4);
      noFill();
  
      for(let i=1; i<boardSize; ++i) {
        line(0, h*i, width, h*i);
        line(w*i, 0, w*i, height);
      }
  
      for(let i=0; i<boardSize; ++i) {
        for(let j=0; j<boardSize; ++j) {
          let x=(w*j)+(w/2);
          let y=(h*i)+(h/2);
          let xr = w/4;
          let yr = h/4;
          if(board[i][j]==user1) {
            line(x-xr, y-yr, x+xr, y+yr);
            line(x+xr, y-yr, x-xr, y+yr);
          }
          else if(board[i][j]==user2) {
            ellipseMode(CENTER);
            ellipse(x, y, xr*2, yr*2);
          }
        }
      }
  
      winner = isWinner();
      if(winner) {
        if(winner == 'TIE')
          resultText.innerHTML = (winner);
        else
          resultText.innerHTML = (winner + ' is Winner');
        isloop = false
      }
    }
  }
</script>